# Generated by Django 5.2.8 on 2026-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_amout_to_use_coupon',
            field=models.PositiveBigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
