# Generated by Django 6.0.1 on 2026-04-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='thunbnail',
            new_name='thumbnail',
        ),
    ]
