# Generated by Django 5.2.8 on 2026-04-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desctiption',
            new_name='description',
        ),
    ]
